markdown: kramdown
permalink: /:title 
title: 书单
url: https://metaldudu.github.io/book-lists
subscribe: https://metaldudu.github.io/book-lists/feed
exclude: [ README.md, newpost.rb ]
domain: mrdu.me
author: metaldudu
email: metaldudu@gmail.com
twitterID: metaldudu
disqusShortname: metaldudu
safe: true
