markdown: kramdown
permalink: /:year/:title 
title: 读写卡片
url: https://mrdu.me/cards
subscribe: https://mrdu.me/cards/feed
exclude: [ README.md, newpost.rb ]
domain: mrdu.me
author: metaldudu
email: metaldudu@gmail.com
twitterID: metaldudu
disqusShortname: metaldudu
safe: true