markdown: kramdown
permalink: /:title 
title: 文摘
url: https://metaldudu.github.io/txt
subscribe: https://metaldudu.github.io/txt/feed
exclude: [ README.md, newpost.rb ]
domain: mrdu.me
author: metaldudu
email: metaldudu@gmail.com
twitterID: metaldudu
disqusShortname: metaldudu
safe: true
